pipe:
  path_root: "payload"
  transform:
    strip:
      - "id"
      - "numero-registro"
      - "outros-numeros"
      - "situacao"
      - "denominacao"
      - "titulo"
      - "autor"
      - "classificacao"
      - "resumo-descritivo"
      - "dimensoes"
      - "dimensoes-altura"
      - "dimensoes-largura"
      - "dimensoes-peso"
      - "dimensoes-profundidade-comprimento"
      - "dimensoes-espessura"
      - "dimensoes-diametro"
      - "material-tecnica"
      - "estado-conservacao"
      - "local-producao"
      - "data-producao"
      - "condicoes-reproducao"
      - "midias-relacionadas"
      - "url"
    lowercase:
      - "url"
      - "dimensoes"
      - "dimensoes-altura"
      - "dimensoes-largura"
      - "dimensoes-peso"
      - "dimensoes-profundidade-comprimento"
      - "dimensoes-espessura"
      - "dimensoes-diametro"
    split:
      material-tecnica:
        - "|"
      classificacao:
        - ">"
        - "&gt;"
    capitalize:
      - "classificacao"
    add_hash:
      target: "hash"
      method: "md5"
  target_collection:
    connection_name: "brasiliana.local"
    collection_id: "5"
    metadata:
      "37": "id"
      "7": "resumo-descritivo"
      "8": "titulo"
      "32": "numero-registro"
      "31": "outros-numeros"
      "29": "situacao"
      "30": "denominacao"
      "28": "autor"
      "24": "dimensoes"
      "25": "dimensoes-altura"
      "26": "classificacao"
      "23": "dimensoes-largura"
      "20": "dimensoes-espessura"
      "21": "dimensoes-profundidade-comprimento"
      "22": "dimensoes-diametro"
      "18": "dimensoes-peso"
      "118561": "material-tecnica"
      "14": "data-producao"
      "16": "local-producao"
      "32429": "estado-conservacao"
      "15": "condicoes-reproducao"
      "13": "midias-relacionadas"
      "33": "museu"
      "35": "fingerprint"
      "36": "url"
      "32221": "colecao"
      "32413": "cidade"
      "32417": "uf"
      "_thumbnail": "thumbnail"
      "_document": "document"
