pipe:
  path_root: "payload"
  transform:
    strip:
      - "id"
      - "numero-registro"
      - "outros-numeros"
      - "situacao"
      - "denominacao"
      - "titulo"
      - "autor"
      - "classificacao"
      - "resumo-descritivo"
      - "dimensoes"
      - "dimensoes-altura"
      - "dimensoes-largura"
      - "dimensoes-peso"
      - "dimensoes-profundidade-comprimento"
      - "dimensoes-espessura"
      - "dimensoes-diametro"
      - "material-tecnica"
      - "estado-conservacao"
      - "local-producao"
      - "data-producao"
      - "condicoes-reproducao"
      - "midias-relacionadas"
      - "url"
    lowercase:
      - "url"
      - "dimensoes"
      - "dimensoes-altura"
      - "dimensoes-largura"
      - "dimensoes-peso"
      - "dimensoes-profundidade-comprimento"
      - "dimensoes-espessura"
      - "dimensoes-diametro"
    split:
      material-tecnica:
        - "|"
      classificacao:
        - ">"
        - "&gt;"
    capitalize:
      - "classificacao"
    add_hash:
      - target: "fingerprint"
        method: "md5"
        fields:
          id: null
          museu: null
          "numero-registro": null
      - target: "hash-content"
        method: "md5"
        fields:
          "id": null
          "resumo-descritivo": null
          "titulo": null
          "numero-registro": null
          "outros-numeros": null
          "situacao": null
          "denominacao": null
          "autor": null
          "dimensoes": null
          "dimensoes-altura": null
          "classificacao": null
          "dimensoes-largura": null
          "dimensoes-espessura": null
          "dimensoes-profundidade-comprimento": null
          "dimensoes-diametro": null
          "dimensoes-peso": null
          "material-tecnica": null
          "data-producao": null
          "local-producao": null
          "estado-conservacao": null
          "condicoes-reproducao": null
          "midias-relacionadas": null
          "museu": null
          "url": null
          "colecao": null
          "cidade": null
          "uf": null
  target_collection:
    connection_name: "brasiliana.local"
    collection_id: "5"
    metadata_identifier: "35" # metadado no agregador que guarda o identificador unico dos itens no processe de agregação
    metadata_hash_content: "4991391"
    ignore_items_without_identifier: true # ignorar o item caso não tenha o metadado identificador
    metadata:
      "37": "id"
      "7": "resumo-descritivo"
      "8": "titulo"
      "32": "numero-registro"
      "31": "outros-numeros"
      "29": "situacao"
      "30": "denominacao"
      "28": "autor"
      "24": "dimensoes"
      "25": "dimensoes-altura"
      "26": "classificacao"
      "23": "dimensoes-largura"
      "20": "dimensoes-espessura"
      "21": "dimensoes-profundidade-comprimento"
      "22": "dimensoes-diametro"
      "18": "dimensoes-peso"
      "118561": "material-tecnica"
      "14": "data-producao"
      "16": "local-producao"
      "32429": "estado-conservacao"
      "15": "condicoes-reproducao"
      "13": "midias-relacionadas"
      "33": "museu"
      "35": "fingerprint"
      "36": "url"
      "32221": "colecao"
      "32413": "cidade"
      "32417": "uf"
      "4991391": "hash-content"
      "_thumbnail": "thumbnail"
      "_document": "document"
